server:
  port: 8866

spring:
  data:
    mongodb:
      host: 47.100.105.136
      port: 27017
      database: post
      password: mengyuanyun
      username: guiyun
      authentication-database: admin
  redis:
    # 地址
    host: 47.100.105.136
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
obs:
  huawei:
    ak: TSTPOQYY2JCI9BBHLIPW
    sk: lchouQgxP84l2GVPwkSppLsdurvLCflbpw2kulvd
    end-point: https://obs.cn-east-3.myhuaweicloud.com
